export enum ETableColumnType {
    TEXT = 'TEXT',  // TEXT
    ACTIONS = 'ACTIONS',
    STATUS = 'STATUS', // HIỂN THỊ KIỂU THẺ TAG
    ICON_EXPANDED = 'ICON_EXPANDED',
    ACTION_DROPDOWN = 'ACTION_DROPDOWN',    // (FUNCTIONS) LIST ACTION
    RENDER = 'RENDER',
    NUMBER = 'NUMBER',
    DATE = 'DATE',
    FILE = 'FILE',
    // CHUA SU DUNG
    REORDER = "REORDER",    // KÉO THẢ
    IMAGE = "IMAGE",    // IMAGE
    CHECKBOX_ACTION = 'CHECKBOX_ACTION',    // CHECKBOX CÓ THỂ TICK
    // CHECKBOX_CHANGE = 'CHECKBOX_CHANGE',    // CHECKBOX XỬ LÝ GỌI HÀM
    // CHECKBOX_SHOW = 'CHECKBOX_SHOW',    // CHECKBOX CHỈ ĐỂ SHOW
    CURRENCY = 'CURRENCY',  // KIỂU TIỀN TỆ (pipe)
    ACTION_BUTTON = 'ACTION_BUTTON',    // (FUNCTION) GIỐNG ACTION_ICON CHỈ KHÁC VỀ MẶT HIỂN THỊ
    ACTION_ICON = 'ACTION_ICON',    // (FUNCTION)
    ICON = 'ICON',
    LINK = 'LINK', // TEXT LINK
}